name: "Build"

on:
  push:
    branches:
      - master

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Copy to docs/
        run: mv docs/_includes/ _includes && mv docs/_layouts/ _layouts && mv docs/_config.yml _config.yml && mv docs/CNAME CNAME && rm -rf docs && cp -r markdown docs && mv _includes docs/_includes && mv _layouts docs/_layouts && mv _config.yml docs/_config.yml && mv CNAME docs/CNAME && cd docs/ && mv *.md index.md && cd ..
      - name: Adjust relative links (naively, might break things) & prerender KaTeX
        run: cd docs && ../scripts/replacer.sh
      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Create commit
        run: |
          git add -A
          git diff-index --quiet HEAD || (git commit -m "[RELEASE] Automatic build" && git push origin master)
