name: "Notion update"

on:
  push:
    branches:
      - master
  schedule:
    -   cron: "0 * * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install LFS
        run: git lfs install
      - name: Checkout LFS objects
        run: git lfs checkout
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Setup dependencies
        run: npm install -g notion-backup-d3psi
      - name: Run backup
        run: notion-backup
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_ID: ${{ secrets.NOTION_ID }}
          NOTION_SPACE_ID: ${{ secrets.NOTION_SPACE }}
      - name: rm -rf *.zip && rm -rf *.pdf
      - name: Track LFS files
        run: find ./* -size +100M -exec git lfs track "{}" \;
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Create commit
        run: |
          git add -A
          git commit -m "Automatic snapshot"
          git push origin master
